import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" data-theme="light">
      <body className="max-w-7xl m-auto">
        <Navbar></Navbar>
        <main>
        {children}
        </main>
      </body>
    </html>
  );
}
